### ISSUE TITLE
Couldn't read /tmp/885.305671111809-black_list.rules

### ISSUE THREAD

**Issue by maravento** [amabrouki/snort#1]
Couldn't read /tmp/885.305671111809-black_list.rules - No such file or directory
 at /usr/local/bin/pulledpork.pl line 540.
    main::read_iplist(HASH(0x2bd9670), "/tmp/885.305671111809-black_list.rules") called at /usr/local/bin/pulledpork.pl line 431
    main::rulefetch("open", "IPBLACKLIST0", "/tmp/", "http://talosintel.com/feeds/ip-filter.blf") called at /usr/local/bin/pulledpork.pl line 1946

hecking latest MD5 for snortrules-snapshot-2983.tar.gz....
Rules tarball download of snortrules-snapshot-2983.tar.gz....
    They Match
    Done!
Rules tarball download of community-rules.tar.gz....
IP Blacklist download of http://talosintel.com/feeds/ip-filter.blf....
Reading IP List...
The command '/bin/sh -c /usr/local/bin/pulledpork.pl -c /etc/snort/pulledpork.conf -l' returned a non-zero code: 2

Ubuntu zenial 16.04 LTS x64

**Comment by amabrouki** [comment]
Do you still have the problem?
I think you didn't replace <oinkcode> with your own Oinkcode in the pulledpork.conf

**Comment by maravento** [comment]
same problem

**Comment by amabrouki** [comment]
I changed the Dockerfile, and i tested it in different servers.
Delete your local repo and try again.
Clone the new files, change <Oinkcode> in line 19 and 26, and lunch the build.

**Comment by maravento** [comment]
ok. testing.... (thanks)

**Comment by maravento** [comment]
Error 422 when fetching https://www.snort.org/reg-rules/snortrules-snapshot-2983.tar.gz.md5 at /usr/local/bin/pulledpork.pl line 516.
	main::md5file("<Oinkcode>", "snortrules-snapshot-2983.tar.gz", "/tmp/", "https://www.snort.org/reg-rules/") called at /usr/local/bin/pulledpork.pl line 1938

Checking latest MD5 for snortrules-snapshot-2983.tar.gz....
The command '/bin/sh -c /usr/local/bin/pulledpork.pl -c /etc/snort/pulledpork.conf -l' returned a non-zero code: 255

**Comment by amabrouki** [comment]
Can you send me your Pulledprok configuration file (pulledpork.conf) ?

**Comment by maravento** [comment]
Default settings. My installation method is (without changing anything):
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list
sudo apt update && sudo apt -f install && sudo apt -y install docker-engine
sudo usermod -aG docker $(whoami)
sudo systemctl enable docker && sudo systemctl start docker
git clone https://github.com/amabrouki/snort.git
cd snort && sudo docker build -t snort . && cd

that's all

**Comment by amabrouki** [comment]
did you replace &lt;oinkcode&gt; with your own Oinkcode in the pulledpork.conf, before the last command :
cd snort && sudo docker build -t snort . && cd

**Comment by maravento** [comment]
Nop. I only steps you entered. I have not changed ninún file. Installation is with the default values

**Comment by amabrouki** [comment]
Ok, as i said you have to replace &lt;oinkcode&gt; with your own Oinkcode in the pulledpork.conf, before the last command.
This link show how to find your own oinkcode and how to use it : 
[https://snort.org/documents/how-to-find-and-use-your-oinkcode](url)

**Comment by maravento** [comment]
why you do not include everything needed for installation (by default) is complete and does not generate errors, and once completed, the user will then modify the snort rules?

**Comment by amabrouki** [comment]
Yes, it's good idea, but i put the line below in the docker file, to be sure that the user doesn't forget to modify the Oinkcode
`RUN /usr/local/bin/pulledpork.pl -c /etc/snort/pulledpork.conf -l`
If you want to modify the Oinkcode after the build, you can delete this command.

Other thing, i use pulledpurk over oinkmaster.
[http://blog.snort.org/2012/01/importance-of-pulledpork.html](url)

**Comment by maravento** [comment]
You can solve the problem put a tmp Oinkcode, and at the end of the installation, with an "echo", warning message to the user, who must replace the Oinkcode, and giving instructions to replace or use a function like this (to the end of script):
is_oinkcode function () {
read -p "Put your oinkcode here:" oinkcode
oinkcode = `/etc/snort/pulledpork.conf | egrep '^(([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])\.){3}([0-9]{1,2}|1[0-9][0-9]|2[0-4][0-9]|25[0-5])$'`
if [ "$oinkcode"]; Then
-print0 /etc/snort/pulledpork.conf find -type f | xargs -0 -I "{}" sed -i "s: xxxxxxxxxx: $ okicode: g" "{}"
echo "Done"
    fi
}
is_oinkcode

**Comment by amabrouki** [comment]
Thank you for the script. i will test it. 👍 
I can also put the oinkcode as an argument in the "docker run ..." command.

**Comment by maravento** [comment]
Maybe this...

function oinkcode(){
	read -p "Put you oinkcode here: " OINK
	if [ "$OINK" ]; then
	sed -i "s/XXXXXXXXXXXXXXXX/$OINK/g" /etc/snort/pulledpork.conf
   fi
}
oinkcode

while true; do
	read -p "You need to change TMP Oinkcode to real Oinkcode
To get Oinkcode visit https://github.com/amabrouki/snort/issues/url
Do you you want to change oinkcode? (y/n)" answer
    	case $answer in
          [Yy]* )
		# execute command yes
	oinkcode
	echo "OK"
			break;;
          	[Nn]* )
		# execute command no
        echo "bla bla bla.... wherever you want"
			break;;
        * ) echo; echo "Please answer Yes (y) or NO (n).";;
    esac
done

Note: where xxxxxxxxxxxxxxx is a tmp code to replace

**Comment by maravento** [comment]
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)

Initializing machine ID from random generator.
addgroup: The group `systemd-journal' already exists as a system group. Exiting.
Operation failed: No such file or directory

debconf: delaying package configuration, since apt-utils is not installed

**Comment by amabrouki** [comment]
Can you give me the number of STEP in the Docker logs ?

**Comment by maravento** [comment]
Why do not you test your script in a virtual machine running ubuntu 16.04.x x64 commands...

sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "deb https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list
sudo apt update && sudo apt -y install docker-engine
sudo usermod -aG docker $(whoami)
sudo systemctl enable docker && sudo systemctl start docker
git clone https://github.com/amabrouki/snort.git
cd snort && sudo docker build -t snort . && cd

...And review what happens during installation?

**Comment by amabrouki** [comment]
I tested the Dockerfile in Ubuntu 14 and 16.
Currently, we run the container in production server under ubuntu 16:04.
the message that you posted is a blocking message or just a warning?

**Comment by maravento** [comment]
Ah ok... Thanks

**Comment by amabrouki** [comment]
you're welcome
